### ISSUE TITLE
Failed to map data for input while indexing since PhpStorm 2020.3

### ISSUE THREAD

**Issue by theroch** [enriquepiatti/Magicento#316] opened 2020-12-07 16:53 UTC
Magicento 3.1.7
PhpStorm 2020.3

After starting PhpStorm the following error is thrown while indexing:
```
Error while indexing x:\magento\lib\Zend\Amf\Server.php
To reindex this file IDEA has to be restarted

com.intellij.util.indexing.impl.MapReduceIndex$MapInputException: Failed to map data for input 30989 for index php.trivial.pure
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:232)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.updateBaseIndex(MergedInvertedIndex.java:324)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:112)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:38)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1474)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1356)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:555)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1326)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1253)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$2(IndexUpdateRunner.java:251)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:422)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.java:254)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$1(IndexUpdateRunner.java:196)
	at com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection(ProgressSuspender.java:83)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly(IndexUpdateRunner.java:199)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$0(IndexUpdateRunner.java:133)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.diagnostic.PluginException: TypeProvider contract violation? by class com.magicento.extensions.FactoryTypeProvider3 on $method [Plugin: Magicento]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:335)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:59)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.lambda$getTypeFromAST$1(PhpTypeInfo.java:111)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getTypeFromAST(PhpTypeInfo.java:74)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:57)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.PhpTypedElementImpl.getType(PhpTypedElementImpl.java:24)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.getType(VariableImpl.java:631)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveLocal(MemberReferenceImpl.java:138)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveLocal(MemberReferenceImpl.java:80)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolveLocal(MethodReferenceImpl.java:72)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.isPure(PhpSideEffectDetector.java:289)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpFunctionCall(PhpSideEffectDetector.java:170)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpMethodReference(PhpSideEffectDetector.java:165)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:32)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.checkAssignment(PhpSideEffectDetector.java:277)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpAssignmentExpression(PhpSideEffectDetector.java:209)
	at com.jetbrains.php.lang.psi.elements.impl.AssignmentExpressionImpl.accept(AssignmentExpressionImpl.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpElement(PhpSideEffectDetector.java:196)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpStatement(PhpElementVisitor.java:223)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:19)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpElement(PhpSideEffectDetector.java:196)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpGroupStatement(PhpElementVisitor.java:227)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:22)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpElement(PhpSideEffectDetector.java:196)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpForeach(PhpElementVisitor.java:78)
	at com.jetbrains.php.lang.psi.elements.impl.ForeachImpl.accept(ForeachImpl.java:82)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpElement(PhpSideEffectDetector.java:196)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpGroupStatement(PhpElementVisitor.java:227)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:22)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpElement(PhpSideEffectDetector.java:196)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpIf(PhpElementVisitor.java:114)
	at com.jetbrains.php.lang.psi.elements.impl.IfImpl.accept(IfImpl.java:50)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpElement(PhpSideEffectDetector.java:196)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpGroupStatement(PhpElementVisitor.java:227)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:22)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.process(PhpSideEffectDetector.java:281)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector$MyVisitor.visitPhpElement(PhpSideEffectDetector.java:196)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpForeach(PhpElementVisitor.java:78)
	at com.jetbrains.php.lang.psi.elements.impl.ForeachImpl.accept(ForeachImpl.java:82)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.process(PhpSideEffectDetector.java:417)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.canContainSideEffect(PhpSideEffectDetector.java:401)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpSideEffectDetector.canContainSideEffect(PhpSideEffectDetector.java:433)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpTriviallyPureFunctionsIndex$1.processInstruction(PhpTriviallyPureFunctionsIndex.java:141)
	at com.jetbrains.php.codeInsight.controlFlow.PhpInstructionProcessor.processStatementInstruction(PhpInstructionProcessor.java:41)
	at com.jetbrains.php.codeInsight.controlFlow.instructions.impl.PhpStatementInstructionImpl.process(PhpStatementInstructionImpl.java:30)
	at com.jetbrains.php.codeInsight.controlFlow.PhpControlFlowUtil.processSuccessors(PhpControlFlowUtil.java:176)
	at com.jetbrains.php.codeInsight.controlFlow.PhpControlFlowUtil.processSuccessors(PhpControlFlowUtil.java:157)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpTriviallyPureFunctionsIndex.canContainsSideEffect(PhpTriviallyPureFunctionsIndex.java:121)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpTriviallyPureFunctionsIndex.canContainSideEffects(PhpTriviallyPureFunctionsIndex.java:103)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpTriviallyPureFunctionsIndex.isTriviallyPure(PhpTriviallyPureFunctionsIndex.java:60)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:306)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:68)
	at one.util.streamex.StreamEx.toMap(StreamEx.java:1002)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpTriviallyPureFunctionsIndex.lambda$getIndexer$1(PhpTriviallyPureFunctionsIndex.java:51)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:291)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:283)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:168)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:46)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:226)
	... 44 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 99, end 64, length 177
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.magicento.extensions.FactoryTypeProvider3.getClassNameFromSignature(FactoryTypeProvider3.java:191)
	at com.magicento.extensions.FactoryTypeProvider3.getTypeForForeachVar(FactoryTypeProvider3.java:474)
	at com.magicento.extensions.FactoryTypeProvider3.getTypeString(FactoryTypeProvider3.java:600)
	at com.magicento.extensions.FactoryTypeProvider3.getType(FactoryTypeProvider3.java:652)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.lambda$getTypeFromAST$1(PhpTypeInfo.java:100)
	... 133 more
```

**Comment by theroch** [comment] 2020-12-11 08:15
@enriquepiatti
Can you please take a look on this issue?

**Comment by enriquepiatti** [comment] 2020-12-14 10:44
Hi @theroch yes sure I will work on it, I recommend to downgrade to previous PhpStorm version until then, is a problem with versio 2020.3+

**Comment by theroch** [comment] 2021-01-15 09:59
Hi @enriquepiatti is there anything new about this bug?
Do you have a rough timeline on when this bug will be fixed?

**Comment by ghost** [comment] 2021-01-20 10:16
I'm having this problem too and I see it as having critical or near blocker severity as it can cause PhpStorm to not save any input you made after a certain stage (have not investigated in detail when that happens) and when you close the IDE some changes might be lost.

To expand on this: I'm not 100% sure that this is the problem that causes the behaviour I have described but I don't see any other errors in the error report window except this one.

**Comment by enriquepiatti** [comment] 2021-01-21 12:21
I recommend to downgrade PhpStorm for now, remember you can install more than one PhpStorm at once in case you need the latest version for another projects

**Comment by theroch** [comment] 2021-01-26 08:02
Hey @enriquepiatti,
downgrading is not really an option because xdebug 3.x is broken in versions below 2020.3.

**Comment by Alphaegen** [comment] 2021-03-09 10:25
I would like to know whether this issue has been fixed or not. I'm thinking about buying the plugin, but if I can't use the plugin with version 2020.3 that would be a problem for me.

**Comment by enriquepiatti** [comment] 2021-03-09 13:40
@Alphaegen is not fixed at the moment, I recommend to take a look at the plugin developed by Magento team, it's free and they have many developers maintaining it.
Let me know in case you need some features from Magicento2 not included in the official Magento2 plugin, but at the moment I have decided to pause the development on Magicento2 because I cannot compete with a free and official plugin from Magento.

**Comment by theroch** [comment] 2021-03-09 14:06
Hi @enriquepiatti 
in the case of this issue the magicento plugin for magento 1.x is affected.
Will you also discontinue magicento for magento 1.x?
We are still developing with OpenMage so we will use and pay for this plugin in future.
But if you ever decide to discontinue support or development of magicento, maybe it would be possible to release the code as open source so we can fix such problems ourselves?

**Comment by fkruidhof** [comment] 2021-03-11 12:20
@enriquepiatti

Like @theroch I am still developing for Magento 1.x (Mage-One, OpenMage) and will likely continue to do so for at least a year. Since there is no alternative for Magicento for M1, I would love a fix for this issue. Development for M1 without Magicento is a pain....

**Comment by compass2k** [comment] 2021-04-27 01:21
I love how Enrique has abandoned magicento but he's still selling it. I bought it in December and its now decided to unregister itself so I cant use it  but he just ignores my issues post.
Money for nothing and screw the idiot who trusted your word hey?
Anyone know where he's situated so I can take this to his local consumer affairs bureau people need to be warned hes selling 
broken software.

**Comment by magicdude4eva** [comment] 2021-04-27 10:19
I suggest that the owner of repo stops selling the plugin via https://magicento.com/ and then opensources/LGPL the discontinued product so that other people can take over. Would be good if @enriquepiatti  provides a formal statement in the README of this repo and on the website.

**Comment by enriquepiatti** [comment] 2021-04-28 12:34
@compass2k I don't understand your insults, I always reply the emails and I try to do that in the same day. I don't have too much time to update Magicento because Magento1 is discontinued and Magento2 has an official plugin now, but the product stills working, I will update the site to make it clear the last compatible version is 2020.1 (I think it works fine in 2020.2 too). So if you need to use Magicento1 you can just use an older PhpStorm. If you bought it 30 days ago or less you can always ask me for a refund if you think is not useful in your case.
Beside that, if there are too many people with this issue (I didn't receive any complain beside this post) I think I could work on it, but the easiest solution is just to downgrade PhpStorm, you can also install a previous version of xdebug, if you were ok with that technology a few months ago and you are working with an old code (Magento1) anyway, why is so important to work with the latest version of PhpStorm? is not more important to have Magicento1 working for those Magento1 projects thant the extra features you could have from PhpStorm 2020.1+?

**Comment by magicdude4eva** [comment] 2021-04-28 13:55
FWIW - I reached out to Enrique (via the homepage / email) and he promptly responded. I am sure people are frustrated about some decisions and compromises required. sometimes it might be required to upgrade PhpStorm (especially when this is needed due to MacOS upgrades or other operational reasons - for example in our case we needed to upgrade to support fixes in other plugins which were not backwards compatible).

We are have looked at PhpStorm 2021.1.1 with Magicento 1.x and noticed memory issues and shutdowns - unsure if the issue is caused by the plugin.

**Comment by enriquepiatti** [comment] 2021-04-28 18:47
I'm working on this, but at the moment the only workaround is to use a previous PhpStorm version

**Comment by compass2k** [comment] 2021-04-28 20:32
You sell a plugin and then tell people they cant use it with current
software after they find it doesnt work and you're surprised when they
call you bodgy?

You didnt answer my post from over a week ago - even now its ignored so no
9 days no reply is not acceptable.

Basically your app is unusable with current software when you sold it so if
you will refund my non usable licence money
I will delete it and get rid of the annoying messages and broken
functionality.

Instead of getting insulted maybe act like a professional - you took money
for something that doesnt work
if it happened to you I doubt you would be impressed.

d

**Comment by compass2k** [comment] 2021-04-28 22:40
I dont know why he ignored my emails then. He finally replied today but it
was all injured stuff like he was the guy who was sold non working software.

I've asked for a refund but I'm not hopeful.

d

**Comment by enriquepiatti** [comment] 2021-04-29 14:15
@compass2k what is your email? so I can search it in my inbox and your user in Magicento.
Magicento is not my fulltime work as you can guess, sometimes I'm very bussy and I miss some comments here, but I always reply the emails, if is not your case then it's because it didn't arrived to me for some reason (spam etc). 
And of course you can request a refund, that is in the website too, you have 30 days to ask for it, and that means 30 days to test Magicento without risk.

**Comment by enriquepiatti** [comment] 2021-04-30 13:09
@theroch @glamic-ep are you still having this issue? because I cannot reproduce it, if yes please can you send me an email with more details?

**Comment by theroch** [comment] 2021-04-30 13:47
Yes I still have this issue. What info do you need?
I can reproduce this issue while opening a default OpenMage (1.9.x) project.

**Comment by enriquepiatti** [comment] 2021-04-30 13:58
@theroch is that happening only with OpenMage? have you tried some vanilla Magento 1.X?

**Comment by theroch** [comment] 2021-04-30 15:21
Same issue with fresh cloned magento-mirror.
Index always stops on lib\Zend\Amf\Server.php or app\code\core\Mage\Catalog\Model\Product\Type.php

**Comment by enriquepiatti** [comment] 2021-04-30 16:18
@theroch please contact me by email, I'm going to need more details

**Comment by enriquepiatti** [comment] 2021-05-05 16:18
After testing with @theroch we conclude this only happens in PhpStorm 2020.3+ but was fixed in PhpStorm 2021+ so I'm closing this issue

**Closed as completed by enriquepiatti** 2021-05-05 16:18 UTC

**Comment by ghost** [comment] 2021-05-06 06:44
Ok, I also had problems in 2021.1.1 which I sent you per mail.

**Comment by enriquepiatti** [comment] 2021-05-08 23:09
@glamic-ep I don't remember that email, please write me again so we can try to narrow if the problem is from Magicento or some specific version
