### ISSUE TITLE
Sometimes plugin reports that somewho edited .idea/magicento/*xml and propose to restart IDE

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#90] opened 2013-09-21 14:27 UTC
But I haven't touched this files. Also after restarting IDE plugin reports that something is broken and disable the plugin.

**Comment by enriquepiatti** [comment] 2013-09-22 17:11
are you sure you are not editing any file there outside PhpStorm or you are not opening the project multiple times?
please could you put here the full message? 
also, if you are sure that file was not edited then maybe you can omit the warning and not restart the IDE. 
(If Magicento detects an unexpected close of PhpStorm it will be disabled automatically on the next start, just for security, you can quickly enable it again with Alt+M or you can disable this protection from Magicento settings)

**Comment by enriquepiatti** [comment] 2013-11-08 22:41
I'm closing this because I cannot reproduce it, please open again if you have more information.
Thanks !

**Closed as completed by enriquepiatti** 2013-11-08 22:41 UTC
