### ISSUE TITLE
Can't rewrite class

### ISSUE THREAD

**Issue by Zyava** [enriquepiatti/Magicento#47] opened 2013-04-19 12:26 UTC
PhpStorm 6.0.1 (129.291).
Trying to rewrite class - module dropdown is empty. If I press ok button I get exception

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@7896f5ac,notifier=null,catchExceptions=false,when=1366374118294] on apple.awt.CToolkit@52e42811
java.lang.NullPointerException
    at com.magicento.ui.dialog.ChooseModuleDialog.getSelectedModulePath(ChooseModuleDialog.java:152)
    at com.magicento.actions.RewriteClassAction.executeAction(RewriteClassAction.java:48)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:726)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1253)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:708)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:669)
    at java.awt.EventQueue$2.run(EventQueue.java:667)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:678)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:511)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by enriquepiatti** [comment] 2013-05-10 18:25
Please send more details about this Zyava, what class are you trying to rewrite? is this happening with other classes too? is this happening in other projects too?
Thanks !

**Comment by enriquepiatti** [comment] 2013-07-15 01:45
I couldn't reproduce this so I'm closing the issue, please reopen if you are still having this problem.

**Closed as completed by enriquepiatti** 2013-07-15 01:45 UTC
